// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package repository

import (
	"context"
)

const createLink = `-- name: CreateLink :one
INSERT INTO links (short_code, original_url)
VALUES ($1, $2)
RETURNING id, short_code, original_url, created_at
`

type CreateLinkParams struct {
	ShortCode   string `json:"short_code"`
	OriginalUrl string `json:"original_url"`
}

func (q *Queries) CreateLink(ctx context.Context, arg CreateLinkParams) (Link, error) {
	row := q.db.QueryRowContext(ctx, createLink, arg.ShortCode, arg.OriginalUrl)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.ShortCode,
		&i.OriginalUrl,
		&i.CreatedAt,
	)
	return i, err
}

const getClicksByDay = `-- name: GetClicksByDay :many
SELECT DATE(clicked_at)::TEXT AS day, COUNT(*)::INT AS count
FROM clicks
WHERE link_id = $1
GROUP BY DATE(clicked_at)
ORDER BY day
`

type GetClicksByDayRow struct {
	Day   string `json:"day"`
	Count int32  `json:"count"`
}

func (q *Queries) GetClicksByDay(ctx context.Context, linkID int32) ([]GetClicksByDayRow, error) {
	rows, err := q.db.QueryContext(ctx, getClicksByDay, linkID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetClicksByDayRow
	for rows.Next() {
		var i GetClicksByDayRow
		if err := rows.Scan(&i.Day, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getClicksByMonth = `-- name: GetClicksByMonth :many
SELECT DATE_TRUNC('month', clicked_at)::TEXT AS month, COUNT(*)::INT AS count
FROM clicks
WHERE link_id = $1
GROUP BY DATE_TRUNC('month', clicked_at)
ORDER BY month
`

type GetClicksByMonthRow struct {
	Month string `json:"month"`
	Count int32  `json:"count"`
}

func (q *Queries) GetClicksByMonth(ctx context.Context, linkID int32) ([]GetClicksByMonthRow, error) {
	rows, err := q.db.QueryContext(ctx, getClicksByMonth, linkID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetClicksByMonthRow
	for rows.Next() {
		var i GetClicksByMonthRow
		if err := rows.Scan(&i.Month, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLinkByOriginalURL = `-- name: GetLinkByOriginalURL :one
SELECT id, short_code, original_url, created_at
FROM links
WHERE original_url = $1
`

func (q *Queries) GetLinkByOriginalURL(ctx context.Context, originalUrl string) (Link, error) {
	row := q.db.QueryRowContext(ctx, getLinkByOriginalURL, originalUrl)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.ShortCode,
		&i.OriginalUrl,
		&i.CreatedAt,
	)
	return i, err
}

const getLinkByShortCode = `-- name: GetLinkByShortCode :one
SELECT id, short_code, original_url, created_at
FROM links
WHERE short_code = $1
`

func (q *Queries) GetLinkByShortCode(ctx context.Context, shortCode string) (Link, error) {
	row := q.db.QueryRowContext(ctx, getLinkByShortCode, shortCode)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.ShortCode,
		&i.OriginalUrl,
		&i.CreatedAt,
	)
	return i, err
}

const getTotalClicks = `-- name: GetTotalClicks :one
SELECT COUNT(*)::INT AS total
FROM clicks
WHERE link_id = $1
`

func (q *Queries) GetTotalClicks(ctx context.Context, linkID int32) (int32, error) {
	row := q.db.QueryRowContext(ctx, getTotalClicks, linkID)
	var total int32
	err := row.Scan(&total)
	return total, err
}

const recordClick = `-- name: RecordClick :exec
INSERT INTO clicks (link_id, user_agent, ip)
VALUES ($1, $2, $3)
`

type RecordClickParams struct {
	LinkID    int32  `json:"link_id"`
	UserAgent string `json:"user_agent"`
	Ip        string `json:"ip"`
}

func (q *Queries) RecordClick(ctx context.Context, arg RecordClickParams) error {
	_, err := q.db.ExecContext(ctx, recordClick, arg.LinkID, arg.UserAgent, arg.Ip)
	return err
}
