// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"context"
)

type Querier interface {
	CreateLink(ctx context.Context, arg CreateLinkParams) (Link, error)
	GetClicksByDay(ctx context.Context, linkID int32) ([]GetClicksByDayRow, error)
	GetClicksByMonth(ctx context.Context, linkID int32) ([]GetClicksByMonthRow, error)
	GetClicksByUserAgent(ctx context.Context, linkID int32) ([]GetClicksByUserAgentRow, error)
	GetLinkByOriginalURL(ctx context.Context, originalUrl string) (Link, error)
	GetLinkByShortCode(ctx context.Context, shortCode string) (Link, error)
	GetTotalClicks(ctx context.Context, linkID int32) (int32, error)
	RecordClick(ctx context.Context, arg RecordClickParams) error
}

var _ Querier = (*Queries)(nil)
